**Question: Randomly generate a matrix of shape (1Million, 2) and perform below mentioned operations:**

**a. Find the distances between each 2-Dimensional data point from the centroid (i.e. mean) of the given dataset. Append the newly calculated distances as new column with the given dataset.**

**b. Given any data point, generate 3 closest neighbors from it.**

**Approach:**

Step 1 - Randomly generate a matrix of shape 1million * 2

Step 2 - Find the centroid of the data

Step 3 - Compute the distance between 2D datapoints and centroid

Step 4 - Add the distance as a new column to our matrix

In [13]:
#Step 1 - Randomly generate a matrix of shape 1million * 2
import numpy as np  
import random
arr = np.random.randint(100000,size=(1000000,2))
print(arr)

[[51828 86778]
 [62422 84026]
 [65112 23996]
 ...
 [83307 10812]
 [79834 39520]
 [83583  5912]]


In [14]:
#Step 2 - Find the centroid of the data
centroid = np.mean (arr, axis=0)
print(centroid)

[49998.319553 49999.736782]


In [24]:
#Step 3 - Compute the distance between 2D datapoints and centroid
dist=np.sqrt(np.sum((arr-centroid)**2,axis=1))
print(dist)

[36823.74744469 36223.39609189 30076.8625904  ... 51430.99169971
 31622.6613484  55422.55222638]


In [25]:
#Step 4 - Add the distance as a new column to our matrix
np.hstack([arr, dist.reshape(-1,1)])


array([[51828.        , 86778.        , 36823.74744469],
       [62422.        , 84026.        , 36223.39609189],
       [65112.        , 23996.        , 30076.8625904 ],
       ...,
       [83307.        , 10812.        , 51430.99169971],
       [79834.        , 39520.        , 31622.6613484 ],
       [83583.        ,  5912.        , 55422.55222638]])

In [27]:
#Generate random data point
test=np.random.randint(100000,size=(1,2))
print(test)

[[74578 51348]]


In [28]:
#calculate distance between test data and all points in matrix
distances=np.sqrt(np.sum((test - arr)**2,axis=1))
n=3
min_indices=np.argpartition(distances,n-1)[:n]
print(min_indices)

[964524 353788 654126]


In [29]:
#minimum distances
distances[min_indices]

array([52.69724851, 58.13776741, 88.23264702])

In [30]:
#points at minimm distance
arr[min_indices]

array([[74607, 51392],
       [74526, 51374],
       [74662, 51375]])